### PR TITLE
Allow HaRe to compile with ghc 8.0.2 rc1

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by alanz** [comment]
Will this work for rc2?  I am using 

```haskell
#if defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,0,1,1))
```

in `ghc-exactprint`, but we need the opposite sense of it. Perhaps negate the whole thing?

**Comment by alanz** [comment]
@expipiplus1 do you have a configuration that can build all the dependencies? I am battling to build `ghc-mod` at present.

**Comment by expipiplus1** [comment]
This change is the same as the way I fixed things in ghc-mod https://github.com/DanielG/ghc-mod/blob/b859ca7f40c1a6b0a4250497dca1f1c524e08f14/Language/Haskell/GhcMod/Gap.hs#L108

I'll get you a build environment for ghc-mod soon.

**Comment by alanz** [comment]
ghc-mod master branch works fine now, it just needed a bump on directory

**Comment by expipiplus1** [comment]
great, glad you got it working :)

**Comment by alanz** [comment]
This is superseded by https://github.com/RefactoringTools/HaRe/pull/51

**Comment by expipiplus1** [comment]
Super, glad it's working :)

**Pull request closed without merging**
