### PR TITLE
Small changes to Gen Applicative refactoring.

### PR DESCRIPTION
**Pull request by SAdams601**
Two changes to gen applicative. 

1. Added error messages if the target function doesn't exist at the specified position or is not do statement.
2. Removed the function name parameter that was not being used.

### CODE REVIEW

**Comment by alanz** [comment]
You can try making https://github.com/RefactoringTools/HaRe/blob/master/.travis.yml#L72 be

```yaml
 - travis_long  cabal test --show-details=streaming
```

**Comment by SAdams601** [comment]
The travis_long command wasn't found.

**Comment by alanz** [comment]
Oops, should be `./travis_long`

I am sure that used to be there.

**Comment by alanz** [comment]
Its working. The "1 minute elapsed" messages come from 'travis_long'

**Comment by alanz** [comment]
Thanks

**Comment by SAdams601** [comment]
That seems to have done it. Travis_long just prints a message so that travis ci doesn't fail the test for inactivity?

**Pull request merged**
